### ISSUE TITLE
Doesn't support multiple domains with non-unique shortnames

### ISSUE THREAD

**Issue by j-pavel** [peterpakos/checkipaconsistency#39]
### Expected behaviour
- Our environment has subdomains under our realm based on location; e.g., "eastus1.example.com" and "eastus2.example.com"
- Each environment has repeated shortnames; e.g, "freeipa-01.eastus1.example.com" and "freeipa-01.eastus2.example.com"

### Actual behaviour
- When attempting to compare replication across domains, we get the error:
Traceback (most recent call last):
  File "/bin/cipa", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/checkipaconsistency/main.py", line 331, in main
    Main().run()
  File "/usr/lib/python2.7/site-packages/checkipaconsistency/main.py", line 249, in run
    self._print_table()
  File "/usr/lib/python2.7/site-packages/checkipaconsistency/main.py", line 256, in _print_table
    border=not self._args.disable_border
  File "/usr/lib/python2.7/site-packages/prettytable.py", line 122, in __init__
    self.field_names = field_names
  File "/usr/lib/python2.7/site-packages/prettytable.py", line 412, in _set_field_names
    self._validate_option("field_names", val)
  File "/usr/lib/python2.7/site-packages/prettytable.py", line 258, in _validate_option
    self._validate_field_names(val)
  File "/usr/lib/python2.7/site-packages/prettytable.py", line 302, in _validate_field_names
    raise Exception("Field names must be unique!")
Exception: Field names must be unique!

### Steps to reproduce the behaviour
- Setup an environment with repeated shortnames and multiple domains. 
- Invoke cipa using hosts across multiple domains: cipa -H freeipa-01.eastus1.example.com freeipa-02.eastus1.example.com freeipa-01.eastus2.example.com -d example.com -W <blah>

### Version of the project
- 2.7.0

### Version of the FreeIPA
- 4.4

### Version of the Operating System
- CentOS 7.3.1611

**Comment by peterpakos** [comment]
Fixed in 6a1cf52.
