### ISSUE TITLE
Check fails if replication is underway

### ISSUE THREAD

**Issue by j-pavel** [peterpakos/checkipaconsistency#52]
### Expected behaviour
Checks should return a correct result regardless of FreeIPA server activity
### Actual behaviour
Traceback (most recent call last):
  File "/usr/share/checkipaconsistency/bin/cipa", line 11, in <module>
    sys.exit(main())
  File "/usr/share/checkipaconsistency/lib/python2.7/site-packages/checkipaconsistency/main.py", line 331, in main
    Main().run()
  File "/usr/share/checkipaconsistency/lib/python2.7/site-packages/checkipaconsistency/main.py", line 120, in __init__
    self._servers[host] = FreeIPAServer(host, self._domain, self._binddn, self._bindpw)
  File "/usr/share/checkipaconsistency/lib/python2.7/site-packages/checkipaconsistency/freeipaserver.py", line 88, in __init__
    self.hgroups = self._count_hostgroups()
  File "/usr/share/checkipaconsistency/lib/python2.7/site-packages/checkipaconsistency/freeipaserver.py", line 269, in _count_hostgroups
    dn, attrs = results[0]
TypeError: 'bool' object has no attribute '__getitem__'
### Steps to reproduce the behaviour
1.) Initiate a re-initialization from a replica
2.) While the sync is running, run cipa

### Version of the project
2.74
### Version of the FreeIPA
4.4
### Version of the Operating System
CentOS 7.3

**Comment by germanparente** [comment]
This is normal. At re-initialization phase, there's no database. The backend is being re-created.
We could check before starting to query the replica if the database is in state "referral".

More precisely, if "nsslapd-state" is set to "referral", we stop the script.

I will try to implement this as soon as possible.

**Comment by germanparente** [comment]
there are two ways to solve this bug. One is to check the nsslapd-state = referral at database level:

dn: cn=dc\3Dcgparente\2Cdc\3Dlocal,cn=mapping tree,cn=config
result: 0
changetype: modify
replace: nsslapd-state
nsslapd-state: referral

The former is what replication does in the replica being re-initialized.

But as the database is set to referral, there's a second way to fix this and it's to check if a search returns a referral and set the ldap option not to follow referrals. This option has to be set anyway since we want to gather specific information of a node in this cipa.

I will propose a fix for this second case.
