### ISSUE TITLE
Getting error "IndexError: list index out of range"

### ISSUE THREAD

**Issue by AndDeluiz** [peterpakos/checkipaconsistency#65]
### Expected behaviour
No errors since same bindDN and bindPW works with ldapsearch.
ipa_monit user is a IPA user with permission "Read Replication Agreements".

### Actual behaviour
Returns error "IndexError: list index out of range"

**Debug**
```
bash-4.2$ ./.local/bin/cipa --debug
2019-02-15 14:24:28 [main] DEBUG Namespace(binddn=None, bindpw=None, critical=2, debug=True, disable_border=False, disable_header=False, domain=None, hosts=None, log_file=None, nagios_check=None, quiet=False, verbose=False, warning=1)
2019-02-15 14:24:28 [main] DEBUG Initialising...
2019-02-15 14:24:28 [main] DEBUG Loading configuration file /var/run/nrpe/.config/checkipaconsistency
2019-02-15 14:24:28 [main] DEBUG DOMAIN = XXX.YYY.COM.BR
2019-02-15 14:24:28 [main] DEBUG HOSTS = host01, host02
2019-02-15 14:24:28 [main] DEBUG BINDDN = uid=ipa_monit,cn=users,cn=accounts,dc=xxx,dc=yyy,dc=com,dc=br
2019-02-15 14:24:28 [main] DEBUG BINDPW = ********
2019-02-15 14:24:28 [main] DEBUG IPA domain: XXX.YYY.COM.BR
2019-02-15 14:24:28 [main] DEBUG IPA servers: host01, host02
2019-02-15 14:24:28 [freeipaserver] DEBUG Initialising FreeIPA server host01
2019-02-15 14:24:28 [freeipaserver] DEBUG Setting up LDAP connection
2019-02-15 14:24:28 [freeipaserver] DEBUG LDAP connection established
2019-02-15 14:24:28 [freeipaserver] DEBUG Grabbing FQDN from LDAP
2019-02-15 14:24:28 [freeipaserver] DEBUG Search base: cn=config, filter: (objectClass=*), attributes: ['nsslapd-localhost'], scope: 0
Traceback (most recent call last):
  File "./.local/bin/cipa", line 11, in <module>
    sys.exit(main())
  File "/var/run/nrpe/.local/lib/python2.7/site-packages/checkipaconsistency/main.py", line 330, in main
    Main().run()
  File "/var/run/nrpe/.local/lib/python2.7/site-packages/checkipaconsistency/main.py", line 118, in __init__
    self._servers[host] = FreeIPAServer(host, self._domain, self._binddn, self._bindpw)
  File "/var/run/nrpe/.local/lib/python2.7/site-packages/checkipaconsistency/freeipaserver.py", line 65, in __init__
    self._fqdn = self._get_fqdn()
  File "/var/run/nrpe/.local/lib/python2.7/site-packages/checkipaconsistency/freeipaserver.py", line 161, in _get_fqdn
    dn, attrs = results[0]
IndexError: list index out of range
```

**Output from ldapseach**
```
bash-4.2$ ldapsearch -x -h host01.yyy.com.br  -D 'uid=ipa_monit,cn=users,cn=accounts,dc=xxx,dc=yyy,dc=com,dc=br' -b cn=config -W "(objectClass=*)"
Enter LDAP Password:
# extended LDIF
#
# LDAPv3
# base <cn=config> with scope subtree
# filter: (objectClass=*)
# requesting: ALL
#

# 1.3.6.1.4.1.4203.1.9.1.1, features, config
dn: oid=1.3.6.1.4.1.4203.1.9.1.1,cn=features,cn=config
cn: Sync Request Control
objectClass: top
objectClass: directoryServerFeature
oid: 1.3.6.1.4.1.4203.1.9.1.1

# 2.16.840.1.113730.3.4.9, features, config
dn: oid=2.16.840.1.113730.3.4.9,cn=features,cn=config
cn: VLV Request Control
objectClass: top
objectClass: directoryServerFeature
oid: 2.16.840.1.113730.3.4.9

# cn\3Dchangelog, mapping tree, config
dn: cn=cn\3Dchangelog,cn=mapping tree,cn=config
cn: cn=changelog
objectClass: top
objectClass: extensibleObject
objectClass: nsMappingTree

# dc\3Dxxx\2Cdc\3Dyyy\2Cdc\3Dcom\2Cdc\3Dbr, mapping tree, config
dn: cn=dc\3Dxxx\2Cdc\3Dyyy\2Cdc\3Dcom\2Cdc\3Dbr,cn=mapping tree,cn=config
cn: dc=xxx,dc=yyy,dc=com,dc=br
cn: "dc=xxx,dc=yyy,dc=com,dc=br"
objectClass: top
objectClass: extensibleObject
objectClass: nsMappingTree

# o\3Dipaca, mapping tree, config
dn: cn=o\3Dipaca,cn=mapping tree,cn=config
cn: o=ipaca
objectClass: top
objectClass: extensibleObject
objectClass: nsMappingTree

# replica, dc\3Dxxx\2Cdc\3Dyyy\2Cdc\3Dcom\2Cdc\3Dbr, mapping tree, config
dn: cn=replica,cn=dc\3Dxxx\2Cdc\3Dyyy\2Cdc\3Dcom\2Cdc\3Dbr,cn=mapping tre
 e,cn=config
cn: replica
nsDS5Flags: 1
nsDS5ReplicaBindDN: cn=replication manager,cn=config
nsDS5ReplicaId: 4
nsDS5ReplicaName: b4bbf002-d60b11e8-a9fd8ef1-2bb10cb1
nsDS5ReplicaRoot: dc=xxx,dc=yyy,dc=com,dc=br
nsDS5ReplicaType: 3
nsState:: BAAAAAAAAACfuGZcAAAAAAEAAAAAAAAAsAAAAAAAAAAIAAAAAAAAAA==
nsds5ReplicaBackoffMax: 300
nsds5ReplicaLegacyConsumer: off
objectClass: top
objectClass: nsds5replica
objectClass: extensibleobject
nsds5ReplicaChangeCount: 116

# replica, o\3Dipaca, mapping tree, config
dn: cn=replica,cn=o\3Dipaca,cn=mapping tree,cn=config
cn: replica
nsDS5Flags: 1
nsDS5ReplicaBindDN: cn=replication manager,cn=config
nsDS5ReplicaId: 6
nsDS5ReplicaName: 986e8202-d61011e8-a9fd8ef1-2bb10cb1
nsDS5ReplicaRoot: o=ipaca
nsDS5ReplicaType: 3
nsState:: BgAAAAAAAACp42ZcAAAAAAAAAAAAAAAAOhYAAAAAAAAFAAAAAAAAAA==
nsds5ReplicaBackoffMax: 300
nsds5ReplicaLegacyConsumer: off
objectClass: top
objectClass: nsds5replica
objectClass: extensibleobject
nsds5ReplicaChangeCount: 423

# meTohost02.yyy.com.br, replica, dc\3Dxxx\2Cdc\3Dyyy\2Cdc\3Dcom
 \2Cdc\3Dbr, mapping tree, config
dn: cn=meTohost02.yyy.com.br,cn=replica,cn=dc\3Dxxx\2Cdc\3Dyyy\
 2Cdc\3Dcom\2Cdc\3Dbr,cn=mapping tree,cn=config
cn: meTohost02.yyy.com.br
description: me to host02.yyy.com.br
nsDS5ReplicaBindMethod: SASL/GSSAPI
nsDS5ReplicaHost: host02.yyy.com.br
nsDS5ReplicaPort: 389
nsDS5ReplicaRoot: dc=xxx,dc=yyy,dc=com,dc=br
nsDS5ReplicaTransportInfo: LDAP
nsDS5ReplicatedAttributeList: (objectclass=*) $ EXCLUDE memberof idnssoaserial
  entryusn krblastsuccessfulauth krblastfailedauth krbloginfailedcount
nsDS5ReplicatedAttributeListTotal: (objectclass=*) $ EXCLUDE entryusn krblasts
 uccessfulauth krblastfailedauth krbloginfailedcount
nsds50ruv: {replicageneration} 5bcde6e7000000040000
nsds50ruv: {replica 3 ldap://host02.yyy.com.br:389} 5bcde6ec00000003
 0000 5c659f9d000100030000
nsds50ruv: {replica 4 ldap://host01.yyy.com.br:389} 5bcde6e700010004
 0000 5c630669000000040000
nsds5ReplicaStripAttrs: modifiersName modifyTimestamp internalModifiersName in
 ternalModifyTimestamp
nsds5replicaTimeout: 120
nsruvReplicaLastModified: {replica 3 ldap://host02.yyy.com.br:389} 0
 0000000
nsruvReplicaLastModified: {replica 4 ldap://host01.yyy.com.br:389} 0
 0000000
objectClass: nsds5replicationagreement
objectClass: top
objectClass: ipaReplTopoManagedAgreement
nsds5replicaLastUpdateStart: 20190215161828Z
nsds5replicaLastUpdateEnd: 20190215161828Z
nsds5replicaChangesSentSinceStartup:: NDoyNi8xMzkg
nsds5replicaLastUpdateStatus: Error (0) Replica acquired successfully: Increme
 ntal update succeeded
nsds5replicaUpdateInProgress: FALSE
nsds5replicaLastInitStart: 19700101000000Z
nsds5replicaLastInitEnd: 19700101000000Z

# caTohost02.yyy.com.br, replica, o\3Dipaca, mapping tree, config
dn: cn=caTohost02.yyy.com.br,cn=replica,cn=o\3Dipaca,cn=mapping tree
 ,cn=config
cn: caTohost02.yyy.com.br
description: me to host02.yyy.com.br
nsDS5ReplicaBindMethod: SASL/GSSAPI
nsDS5ReplicaHost: host02.yyy.com.br
nsDS5ReplicaPort: 389
nsDS5ReplicaRoot: o=ipaca
nsDS5ReplicaTransportInfo: LDAP
nsDS5ReplicatedAttributeList: (objectclass=*) $ EXCLUDE memberof idnssoaserial
  entryusn krblastsuccessfulauth krblastfailedauth krbloginfailedcount
nsDS5ReplicatedAttributeListTotal: (objectclass=*) $ EXCLUDE entryusn krblasts
 uccessfulauth krblastfailedauth krbloginfailedcount
nsds50ruv: {replicageneration} 5bcdef29000000060000
nsds50ruv: {replica 5 ldap://host02.yyy.com.br:389} 5bcdef3000000005
 0000 5bcdefaa000400050000
nsds50ruv: {replica 6 ldap://host01.yyy.com.br:389} 5bcdef4100000006
 0000 5c65af88000000060000
nsds5ReplicaStripAttrs: modifiersName modifyTimestamp internalModifiersName in
 ternalModifyTimestamp
nsds5replicaTimeout: 120
nsruvReplicaLastModified: {replica 5 ldap://host02.yyy.com.br:389} 0
 0000000
nsruvReplicaLastModified: {replica 6 ldap://host01.yyy.com.br:389} 0
 0000000
objectClass: nsds5replicationagreement
objectClass: top
objectClass: ipaReplTopoManagedAgreement
nsds5replicaLastUpdateStart: 20190215161205Z
nsds5replicaLastUpdateEnd: 20190215161205Z
nsds5replicaChangesSentSinceStartup:: Njo5Ny8wIA==
nsds5replicaLastUpdateStatus: Error (0) Replica acquired successfully: Increme
 ntal update succeeded
nsds5replicaUpdateInProgress: FALSE
nsds5replicaLastInitStart: 19700101000000Z
nsds5replicaLastInitEnd: 19700101000000Z

# search result
search: 2
result: 0 Success

# numResponses: 10
# numEntries: 9
```
### Steps to reproduce the behaviour
* Create an ordinary IPA user with permission "Read Replication Agreements".
* Install checkipaconsistency as README for automatic install using pip.
* Configuration File
```
bash-4.2$ cat .config/checkipaconsistency
[IPA]
domain = XXX.YYY.COM.BR
hosts  = host01, host02
binddn = uid=ipa_monit,cn=users,cn=accounts,dc=xxx,dc=yyy,dc=com,dc=br
bindpw = ********************
```
* Run `cipa`.

### Version of the project
2.7.7
```
bash-4.2$ ./.local/bin/cipa --version
cipa 2.7.7
```
### Version of the FreeIPA
4.6.4
```
ipa-server-common-4.6.4-10.el7.centos.2.noarch
ipa-server-4.6.4-10.el7.centos.2.x86_64
```

### Version of the Operating System
CentOS 7.6
`centos-release-7-6.1810.2.el7.centos.x86_64`

**Comment by peterpakos** [comment]
@AndDeluiz your ldap search is not the same.

Try the following command and see what you get:

`ldapsearch -s base -x -h host01.yyy.com.br  -D 'uid=ipa_monit,cn=users,cn=accounts,dc=xxx,dc=yyy,dc=com,dc=br' -b cn=config -W "(objectClass=*)" nsslapd-localhost`

Then try the same with `-D "cn=Directory Manager"` and compare the results.

As it stands, the tool requires to bind with "cn=Directory Manager". This has been brought up with Red Hat developers in #freeipa multiple times but no workaround exists AFAIK.

I'll work on improving the error output.
